### ISSUE TITLE
Adjustment images in HomePage, news, blog...

### ISSUE THREAD

**Issue by Kvido** [Kvido/Images-HomePage-adjustment#1]
I recommend:
Pictures on the homepage of separation into smaller format.
The main image will be scaled to 100% view formating.
Nebula/css/panel.css
Add

`{
    box-sizing: border-box;
}

img {
    width: 100%;
    height: auto;

}`
I adjust got here:
http://frybtest.euweb.cz/viewpage.php?page_id=1

**Comment by meangczac** [comment]
ok can

**Comment by Kvido** [comment]
Use in connection with the meta tag that we layout.php - "viewport".
It's not exactly an ideal solution because it apparently affects some other pictures on the homepage. Trying still insert CSS into another class of IMG.
In a news blog / settings would be, I think, the optimal set:
File size 800 x 800 h.

**Comment by meangczac** [comment]
You can have them at the main repository. I've invited you into the dev team. I'm figuring out how to stop spam attacks at this moment. Can I leave these to you and robinnn?

**Comment by Kvido** [comment]
Thanks for the invitation, if possible I will understand and do ...
Yes.

**Comment by meangczac** [comment]
Get a github client for windows. Test with your own repo first to check how it works. 👍 

Thank you !

**Comment by Kvido** [comment]
I have Ubuntu 16.04
On my test frybtest site is to show all images on homepage (news, blog, articles, downloads) and their reduction very good! see:
http://frybtest.euweb.cz/viewpage.php?page_id=1

On the second, but the site is stark problémna HomePage for news see .:
https://pc-politika.cz/homepage
Note:
Often saves me at DB column news_name instead of "1" 403 or 417. Seeking the reason why?

**Comment by Kvido** [comment]
//echo "<div class='".$classes." clearfix'>";
echo "<div class='".$classes." clearfix' style='min-height:150px; margin-bottom:20px;'>";
//insert Kvido - 29.03.2017
echo "<div class='m-b-10'><img src='".$data['image']."' class='img-responsive' alt='".$data['cat_name']."' /></div>\n";

**Comment by Kvido** [comment]
```
//echo "<div class='".$classes." clearfix'>";
echo "<div class='".$classes." clearfix' style='min-height:150px; margin-bottom:20px;'>";
//insert Kvido - 29.03.2017
echo "<div class='m-b-10'><img src='".$data['image']."' class='img-responsive' alt='".$data['cat_name']."' /></div>\n";
```

**Comment by Kvido** [comment]
They are resolved images on the HomePage and NEWS BLOG?
I recommend to solve the home.php.
themes/templates/global/home.php
